#!/usr/bin/env python3
"""
gen_project.py - Regenerate the FallingStars.vcxproj source file list.

Scans the src/ tree for *.cpp (ClCompile) and *.h (ClInclude) and rewrites the
block between the FALLINGSTARS_GEN_START / FALLINGSTARS_GEN_END markers in
FallingStars.vcxproj. This means you NEVER edit the project file by hand when
adding or removing source files - just drop them into src/ and re-run this.

Usage:
    python scripts/gen_project.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VCXPROJ = ROOT / "FallingStars.vcxproj"
SRC = ROOT / "src"

START = "<!-- FALLINGSTARS_GEN_START"
END = "FALLINGSTARS_GEN_END -->"


def scan_sources():
    cpp_files = []
    h_files = []
    if not SRC.is_dir():
        print(f"WARNING: src/ directory not found at {SRC}")
        return cpp_files, h_files
    for path in sorted(SRC.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT).as_posix().replace("/", "\\")
        if path.suffix == ".cpp":
            cpp_files.append(rel)
        elif path.suffix == ".h":
            h_files.append(rel)
    return cpp_files, h_files


def build_block(cpp_files, h_files):
    lines = []
    lines.append('  <!-- FALLINGSTARS_GEN_START')
    lines.append('       Regenerated by scripts/gen_project.py. Do not edit by hand. -->')
    lines.append('  <ItemGroup>')
    for rel in cpp_files:
        lines.append(f'    <ClCompile Include="{rel}" />')
    lines.append('  </ItemGroup>')
    lines.append('  <ItemGroup>')
    for rel in h_files:
        lines.append(f'    <ClInclude Include="{rel}" />')
    lines.append('  </ItemGroup>')
    lines.append('  <!-- FALLINGSTARS_GEN_END -->')
    return "\n".join(lines)


def main():
    if not VCXPROJ.is_file():
        print(f"ERROR: {VCXPROJ} not found.")
        sys.exit(1)

    text = VCXPROJ.read_text(encoding="utf-8")
    cpp_files, h_files = scan_sources()
    block = build_block(cpp_files, h_files)

    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(text):
        print("ERROR: gen markers not found in", VCXPROJ.name)
        sys.exit(1)

    # Use a function replacement so backslashes in the generated paths
    # (e.g. "src\Foo.cpp") are not treated as regex escape sequences.
    new_text = pattern.sub(lambda m: block, text)
    VCXPROJ.write_text(new_text, encoding="utf-8")
    print(f"Updated {VCXPROJ.name}: {len(cpp_files)} cpp, {len(h_files)} headers.")


if __name__ == "__main__":
    main()
